---
title: "Week 7: Semantics"
subtitle: "Recitation for LING 201:02"
author: "Quartz Colvin (they/them)"
institute: "Rutgers University"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: ["rutgers", "rutgers-fonts"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      bibliography:  bibliography.bib
    keep_tex: true
header-includes:
- \usepackage{qtree}
- \newenvironment{dummy}{}{}
documentclass: ../includes/tex
---

class: middle, center

# Review!

---

# Review from lecture 

- lexical semantics vs. compositional semantics

- sense vs. reference

--

- possible worlds

- truth values

--

- synonym vs. antonym

- hypernym vs. hyponym





---

class: middle, center

# Semantic relations

---

# Semantic relations 

- **synonym:** words that have the same reference / refer to the same set of things in the world (*drinks* and *beverages*)

- **hypernym:** words whose reference is a _superset_ of another words reference

- **hyponym:** words whose reference is a _subset_ of another words reference

  - *gecko* (hyponym) vs. *lizard* (hypernym)
  
- **antonym:** words that have opposite meanings

  - *subtypes on next slide....*

---

# Semantic relations

- **antonym:** words that have opposite meanings

--

  - **Complementary pairs:** items that can't be in both categories (*alive* vs. *dead*)
  
  - **Gradable pairs:** opposite ends of a scale (*young* vs. *old*)
  
  - **Reverses:** opposite directions (*up* vs. *down*)
  
  - **Converses:** same action, different perspective (*buy* vs. *sell*)

---

# Semantic relations 

Are the following word pairs *synonyms, antonyms,* or a *hypernym-hyponym* pair?

1. bird - avian 

2. bird - sparrow 

3. bird - animal

4. rodent - rat

5. good - evil

6. to clean - to mess up/dirty

--

7. ***more??***

---

class: middle, center

# Entailment:

## sentence **p** entails sentence **q** if and only if **q** is true whenever **p** is true.

### "whenever" there is a possible world where the sentence is true

---

class: middle, center

# Practice: entailment 

---

# Practice: entailment 

For each pair of sentences, does the first sentence **(a)** entail the second sentence **(b)**? 

--

**a.** Charles III is the King of the United Kingdom.

**b.** Queen Elizabeth II was Charles's mother.

--

**a.** I am very very very very very tired.

**b.** I am tired.

--

**a.** Chicken Little believes the sky is falling.

**b.** The sky is falling.

--

**a.** Gible is a silly tabby cat.

**b.** Gible is a cat.

---

# Practice: entailment

For each pair of sentences, does the first sentence **(a)** entail the second sentence **(b)**?

**a.** Bob and Linda live above a restaurant on Ocean Avenue.

**b.** Bob lives above a restaurant on Ocean Avenue.

--

**a.** The kids trick-or-treated on Halloween.

**b.** The kids trick-or-treated in scary costumes on Halloween.

--

**a.** Jake stopped smoking.

**b.** Jake used to smoke.

--

**a.** Keng's car still has Wisconsin license plates on it.

**b.** Keng has a car.





---

# Practice: entailment 

**Think of three sentences that are entailed by each of these sentences:**

1. The spotted lanternfly is an insect that has spread invasively to New Jersey and can cause damage to forests and fruit crops.

2. The starship Enterprise explored strange new worlds, sought out new life and new civilizations, and boldly went where no one had gone before.

3. Controversially, DeLa chose to eliminate herself from the competition after winning the lip-sync battle, which allowed Trixie, Kennedy, and Shangela to all stay in the competition.

4. Mario defeated Bowser, but then all he found in the dungeon was Toad, who told him that the princess was in another castle.

---

# Coming up 

### Reading 

- read the semantics reading **Fromkin Ch7**, if you haven't yet!

### Homework 

- NONE UNTIL OCT 26!



